// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myyyvzkhlxcxlipionvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15eXl2emtobHhjeGxpcGlvbnZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTMyMjAsImV4cCI6MjA2MzU4OTIyMH0.y6dNt17ns-vNxwtI7mVkYu0cWDJcUMzobIkq9nKE650";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});